### ISSUE TITLE
Wrong association of modules with plugins.

### ISSUE THREAD

**Issue by khmarbaise** [takari/maven-profiler#7]
Hi,
i have a project which contains multiple modules https://github.com/khmarbaise/javaee (branch maven-profiler including the log output mvn.log) and if i configured maven-profiler accordingly (using Maven 3.1.1) i can run maven via mvn clean package -Dmaven.profile and got output like this:

com.soebes.examples.j2ee:parent:1.0.4-SNAPSHOT

  clean 87ms
    org.apache.maven.plugins:maven-clean-plugin:2.5 (default-clean) 87ms

  validate 271ms
    org.apache.maven.plugins:maven-enforcer-plugin:1.3.1 (enforce-maven) 271ms

com.soebes.examples.j2ee:domain:1.0.4-SNAPSHOT

  package 738ms
    org.apache.maven.plugins:maven-site-plugin:3.3 (attach-descriptor) 691ms

But i have realized that the output does not contain the correct information about a module (assembly):

Furthermore i realized that the association between the printed module name and the executed plugins is not correct:

com.soebes.examples.j2ee:assembly:1.0.4-SNAPSHOT

  package 1s 326ms
    org.apache.maven.plugins:maven-jar-plugin:2.4 (default-jar) 5ms
    org.apache.maven.plugins:maven-site-plugin:3.3 (attach-descriptor) 1ms
    org.apache.maven.plugins:maven-shade-plugin:2.2 (test) 511ms
    org.apache.maven.plugins:maven-shade-plugin:2.2 (dev) 373ms
    org.apache.maven.plugins:maven-shade-plugin:2.2 (prod) 355ms

  clean 3ms
    org.apache.maven.plugins:maven-clean-plugin:2.5 (default-clean) 3ms

  validate 22ms
    org.apache.maven.plugins:maven-enforcer-plugin:1.3.1 (enforce-maven) 22ms

In this module there is no execution of the maven-shade-plugin cause the name of the module: assembly gives the information that here the maven-assembly-plugin should have run which can be seen in the maven output but not in the profiler output...

I also checked using mvn package alone but this does not change a thing.

**Comment by cstamas** [comment]
fix is in
